### PR TITLE
Adding support to let poeple create npm templates

### PR DESCRIPTION
**Pull request by demetriusj**
Hi TJ,

ngen is great and i wanted to add support to let people and my self create new templates easily. I though it would be cool if you could have a npm package as a template. So I added a flag to let ngen look up a npm package. The hope was to let people have private templates in their local npm repository and public packages. I also created an example template hoping that would help people using ngen.

PS. I love your work! We are about to roll out a large site that was built using a lot of projects you wrote and committed to. I really love the nodejs community and trying to find a way to contribute back. Thank you for all your hard work and really COOL software!

### CODE REVIEW

**Comment by tj** [comment]
cool man, i like the idea, it was initially just to scratch my itch of creating the same damn structure each time haha but yeah this is good

**Comment by demetriusj** [comment]
thanks, let me know if you need me to do anything! have an awesome day.

**Comment by tj** [comment]
why did you close? haha. oddly it wont apply for some reason, git wont leave the conflict for me to merge

**Comment by demetriusj** [comment]
My bad sorry, I am new to github and this was my frist pull request and hopefully will not be my last hehe

**Comment by tj** [comment]
i'll have to try and get it to apply later, git is being strange

**Comment by demetriusj** [comment]
Sounds good, I will pray to the git unicorns

**Comment by demetriusj** [comment]
Hi TJ,
Do I need to do anything to help with git? Did I create a problem for you in the way I checked in my code and merge the branch. Please let me know if you need me to do anything to help.

**Comment by tj** [comment]
not sure what's going on, git just gives me a bunch of "cannot merge" messages but doesnt even leave the conflict for me to edit

**Pull request closed without merging**
