### PR TITLE
Making it possible to define dynamic variables

### PR DESCRIPTION
**Pull request by Gozala**
It's quite annoying to specify  user / email every time I create package so I thought why not use git to read this data from config. This change makes it possible to  define dynamic variables as functions that can run 'git --bare config --global user.name' to read user out and pass it back to the ngen.

Change also adds template that uses this functionality to read out user name and email from config.

### CODE REVIEW

**Comment by Gozala** [comment]
@visionmedia can you please respond in some form, to let me know if you're willing to pull this change in ?

**Comment by tj** [comment]
hey sorry, didn't see this. i will take a look

**Comment by tj** [comment]
looks good, merging

**Comment by Gozala** [comment]
Awesome thanks @visionmedia

**Pull request merged**
